### ISSUE TITLE
Pixel perfect port?

### ISSUE THREAD

**Issue by gmarty** [pomle/megamanjs#34]
Hi, are you still working actively on this project?

Are you looking to make a pixel perfect port? If so, maybe you could use a JavaScript emulator running the original game in the tests. The idea is to compare a few frames from this game and the emulator and make sure you get the same result from a similar set of commands (like jump, shoot, run...). This could be used to test the levels and enemies behaviour too.

**Comment by pomle** [comment]
Hello!

Thanks for the tip. If my estimations fail for some reason, I might try this. At this point I just measure pixels and frames manually using an emulator to get the correct velocities.

Some aspects of the game intend to improve on limitations incurred by the Nintendo hardware. Exactly what was never decided, but I have decided to not respawn enemies that respawn because of bugs and enemies will be able to damage each other.
